name: Desktop App

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Go
      uses: actions/setup-go@v1.0.0
      with:
        version: 1.13
    - name: Setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash
    - name: go get dependencies
      run: |
        go get -d ./desktop-app/...
    - name: Install astilectron-bundler
      run: |
        go get -u github.com/asticode/go-astilectron-bundler/...
        go install github.com/asticode/go-astilectron-bundler/astilectron-bundler
    - name: npm install and bin-build
      run: |
        npm ci
        npm run bin-build --if-present
        ls desktop-app/output/linux-amd64
    - uses: actions/upload-artifact@v1
      with:
        name: Yggdrasil
        path: desktop-app/output/linux-amd64
      env:
        CI: true
