name: Create Release Binaries

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Go
      uses: actions/setup-go@v1.0.0
      with:
        version: 1.13
    - name: Setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash
    - name: go get dependencies
      run: |
        go get -d ./desktop-app/...
    - name: Install astilectron-bundler
      run: |
        go get -u github.com/asticode/go-astilectron-bundler/...
        go install github.com/asticode/go-astilectron-bundler/astilectron-bundler
    - name: npm install and bin-build
      run: |
        npm ci
        npm run bin-build --if-present
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./desktop-app\output\windows-amd64\Yggdrasil.exe
          asset_name: Yggdrasil-Win64.exe
          asset_content_type: application/octet-stream
